version: 2
jobs:
  build:
    working_directory: ~/expense-tracker-api
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      - image: postgres:11.1
        environment:
          POSTGRES_USER: expense_tracker_api
          POSTGRES_DB: database_test
          POSTGRES_PASSWORD: expense_tracker_api_pass123

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    steps:
      - checkout
      # Download and cache dependencies
      - run:
        name: update_yarn
        command: "sudo npm install -g yarn@latest"
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: # run tests!
          name: test
          environment:
            TEST_DATABASE_USERNAME: expense_tracker_api
            TEST_DATABASE: database_test
            TEST_DATABASE_PASSWORD: expense_tracker_api_pass123
            JWT_SECRET: thisIsACICDSecretOkayYesLetsMoveOnNow
          command: yarn test
